# Generated by Django 3.1.2 on 2020-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201220_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='image',
            field=models.ImageField(upload_to='Pictures/'),
        ),
    ]
