# Generated by Django 3.1.2 on 2020-12-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201220_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='image',
            field=models.ImageField(upload_to='myapp/images'),
        ),
    ]
